language: ruby

branches:
  only:
    - master

before_script:
  - curl -o /tmp/cf-linux-64.tgz https://cli.run.pivotal.io/stable\?release\=linux64-binary\&version\=6.23.1\&source\=github-rel
  - tar -xvf /tmp/cf-linux-64.tgz
  - export PATH=$PATH:$PWD/

rvm:
  - '2.2.6'
  - '2.3.3'
  - '2.4.0'

script: 'bundle exec rake test'
