language: ruby

branches:
  only:
    - master

before_script:
  - wget http://go-cli.s3-website-us-east-1.amazonaws.com/releases/latest/cf-linux-amd64.tgz -O /tmp/cf-linux-amd64.tgz
  - tar -xvf /tmp/cf-linux-amd64.tgz
  - export PATH=$PATH:$PWD/

rvm:
  - '2.2.6'
  - '2.3.3'
  - '2.4.0'

script: 'bundle exec rake test'
