language: ruby

branches:
  only:
    - master

before_script:
  - curl -o /tmp/cf-linux-64.tgz https://s3-us-west-1.amazonaws.com/cf-cli-releases/releases/v6.23.1/cf-cli_6.23.1_linux_x86-64.tgz
  - tar -xvf /tmp/cf-linux-64.tgz
  - export PATH=$PATH:$PWD/

rvm:
  - '2.2.6'
  - '2.3.3'
  - '2.4.0'

script: 'bundle exec rake test'
